### ISSUE TITLE
Use AngularJS one-time binding when possible

### ISSUE THREAD

**Issue by grena** [grena/gruik#35]
By following this http://toddmotto.com/angular-one-time-binding-syntax/, performances could be increased on static lists.

**Comment by flasheater** [comment]
Are you referring to lists such as these : http://gruik.io/view/278 ? If so, where is the performance problem?

**Comment by grena** [comment]
Hi @flasheater, no I was referring to list generated by AngularJS, such as [dashboard](http://gruik.io/dashboard) or [explore](http://gruik.io/explore). 

It's for sure not a real issue since it loads fast, but a best practice to disabled data-binding when not necessary :)
