### ISSUE TITLE
error in readme / How to install?

### ISSUE THREAD

**Issue by jniggemann** [grena/gruik#38]
This is the software I have been searching for!
In the "How to install?" chapter you mention a file `app/config/local/database.php`, however there's no directory called 'local' under `app/config/`...
I'm quite sure it's `app/config/database.php`, is it?

**Comment by grena** [comment]
Hi jniggemann !

In fact, Laravel can manage multiple environment, by creating subdirectories in `app/config`. If you don't care about it, you can directly edit the `app/config/database.php` file, yes :)

**Comment by RoPe93** [comment]
I cannot run composer command, what do I need to install?

**Comment by wbrbr** [comment]
You need to install [composer](https://getcomposer.org/)

**Comment by jniggemann** [comment]
Got it up and running :-) Thank you and keep up the good work!
