### ISSUE TITLE
Idea: "Private" gruik

### ISSUE THREAD

**Issue by jniggemann** [grena/gruik#44]
I'd like to use gruik with only one user (myself), other users should not be able to sign up.
Is that already possible? If not, I'd like to propose this as a feature.

**Comment by grena** [comment]
Hello @jniggemann, 
I currently move Gruik project to Symfony2, no ETA yet, but it's a nice feature I'd like to have.

**Comment by jniggemann** [comment]
Hi @grena,

is there something I could help with? Gruik as a symfony-based application could really be a killer-app for a personal knowledgebase...

**Comment by jniggemann** [comment]
timeout, closing...
